on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: github.event.pull_request.commits
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: git rev-list --all
      - if: github.event_name == 'pull_request'
        run: python lint.py ${{ format('{0}..{1}', github.event.pull_request.base.sha, github.event.pull_request.head.sha) }}
      - if: github.event_name == 'push'
        run: python lint.py ${{ format('{0}..{1}', github.event.after, github.event.head_commit.id) }}
